name: hyphen
description: "A cross-platform Flutter package that provides high-quality word hyphenation."
version: 0.4.0
homepage: https://github.com/tstumpSC/hyphen
issue_tracker: https://github.com/tstumpSC/hyphen/issues
repository: https://github.com/tstumpSC/hyphen

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  characters: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - test/assets/test_dictionary.dic

topics:
  - hyphenation
  - hyphen
  - dart
  - text
