name: hyphen
description: "A cross-platform Flutter plugin that provides high-quality word hyphenation."
version: 0.1.3
homepage: https://github.com/tstumpSC/hyphen
issue_tracker: https://github.com/tstumpSC/hyphen/issues
repository: https://github.com/tstumpSC/hyphen

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.1.4
  web: ^1.1.1
  http: ^1.5.0
  path: ^1.9.1
  characters: ^1.4.0

dev_dependencies:
  ffigen: ^19.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true

  assets:
    - web/assets/hyphen.js
    - web/assets/hyphen.wasm
    - test/assets/test_dictionary.dic

topics:
  - hyphenation
  - hyphen
  - ffi
  - wasm